export interface ToolDirectoryItem {
  name: string;
  primaryCategory: string;
  secondaryCategory: string;
  url: string;
}

export const toolsDirectory: ToolDirectoryItem[] = [
  { name: 'Abacus.AI', primaryCategory: 'AI Builders', secondaryCategory: 'LLM Proxy', url: 'https://chatllm.abacus.ai/' },
  { name: 'Aha!', primaryCategory: 'Product Management', secondaryCategory: 'Roadmapping', url: 'https://www.aha.io/' },
  { name: 'Ahrefs', primaryCategory: 'SEO', secondaryCategory: 'SEO Tools', url: 'https://ahrefs.com/' },
  { name: 'Airtable', primaryCategory: 'Database', secondaryCategory: 'No-code Database & Apps', url: 'https://www.airtable.com/' },
  { name: 'AppSumo', primaryCategory: 'Marketplace', secondaryCategory: 'Software Deals', url: 'https://appsumo.com/' },
  { name: 'Apollo', primaryCategory: 'CRM', secondaryCategory: 'Sales Intelligence', url: 'https://www.apollo.io/' },
  { name: 'Atlassian', primaryCategory: 'Productivity', secondaryCategory: 'Project Management Suite', url: 'https://www.atlassian.com/' },
  { name: 'Attio', primaryCategory: 'CRM', secondaryCategory: 'Relationship Management', url: 'https://www.attio.com/' },
  { name: 'Beehiiv', primaryCategory: 'Newsletter', secondaryCategory: 'Email Marketing', url: 'https://www.beehiiv.com/' },
  { name: 'bolt.new', primaryCategory: 'AI Builders', secondaryCategory: 'Web Development', url: 'https://bolt.new/' },
  { name: 'Builder.io', primaryCategory: 'App Builders', secondaryCategory: 'Visual CMS/Builder', url: 'https://www.builder.io/' },
  { name: 'Buffer', primaryCategory: 'Social Media', secondaryCategory: 'Social Scheduling', url: 'https://buffer.com/' },
  { name: 'Cal.com', primaryCategory: 'Scheduling', secondaryCategory: 'Open-source Scheduling', url: 'https://cal.com/' },
  { name: 'Canva', primaryCategory: 'Design', secondaryCategory: 'Graphic/Doc Design', url: 'https://www.canva.com/' },
  { name: 'ChatGPT', primaryCategory: 'AI Models', secondaryCategory: 'Conversational AI', url: 'https://chatgpt.com/' },
  { name: 'ChatPDF', primaryCategory: 'Document AI', secondaryCategory: 'PDF Q&A', url: 'https://www.chatpdf.com/' },
  { name: 'Circle', primaryCategory: 'Community', secondaryCategory: 'Platform', url: 'https://circle.so/' },
  { name: 'Clarity (Microsoft)', primaryCategory: 'Analytics', secondaryCategory: 'Session Replay', url: 'https://clarity.microsoft.com/' },
  { name: 'Claude', primaryCategory: 'AI Models', secondaryCategory: 'Conversational AI', url: 'https://claude.ai/' },
  { name: 'Clay', primaryCategory: 'CRM', secondaryCategory: 'Data Enrichment', url: 'https://www.clay.com/' },
  { name: 'Codeium', primaryCategory: 'AI Builders', secondaryCategory: 'Code Assistant', url: 'https://codeium.com/' },
  { name: 'Copy.ai', primaryCategory: 'Generative AI', secondaryCategory: 'Copywriting', url: 'https://www.copy.ai/' },
  { name: 'Cursor', primaryCategory: 'AI Builders', secondaryCategory: 'AI-first Code Editor', url: 'https://www.cursor.com/' },
  { name: 'Databutton', primaryCategory: 'AI App Builder', secondaryCategory: 'Hosted IDE + DB', url: 'https://databutton.com/' },
  { name: 'DeepSeek', primaryCategory: 'AI Models', secondaryCategory: 'Open-source/Efficient LLMs', url: 'https://www.deepseek.com/' },
  { name: 'Devin', primaryCategory: 'AI Builders', secondaryCategory: 'AI Engineer', url: 'https://devin.ai/' },
  { name: 'Discord', primaryCategory: 'Communications', secondaryCategory: 'Community Chat', url: 'https://discord.com/' },
  { name: 'ElevenLabs', primaryCategory: 'Generative AI', secondaryCategory: 'Voice/TTS', url: 'https://elevenlabs.io/' },
  { name: 'Feather', primaryCategory: 'Web Builder', secondaryCategory: 'Notion Sites', url: 'https://feather.so/' },
  { name: 'Figma', primaryCategory: 'Design', secondaryCategory: 'UI/UX Design', url: 'https://www.figma.com/' },
  { name: 'Firebase', primaryCategory: 'Backend', secondaryCategory: 'Realtime DB, Auth, Hosting', url: 'https://firebase.google.com/' },
  { name: 'FlutterFlow', primaryCategory: 'App Builders', secondaryCategory: 'Low-code Mobile (Flutter)', url: 'https://www.flutterflow.io/' },
  { name: 'Framer', primaryCategory: 'Design', secondaryCategory: 'Website Builder', url: 'https://www.framer.com/' },
  { name: 'Galileo AI', primaryCategory: 'Generative AI', secondaryCategory: 'UI Design', url: 'https://www.usegalileo.ai/' },
  { name: 'Gemini', primaryCategory: 'AI Models', secondaryCategory: 'Multimodal Assistant', url: 'https://gemini.google.com/app' },
  { name: 'Glide', primaryCategory: 'App Builders', secondaryCategory: 'Apps from Spreadsheets', url: 'https://www.glideapps.com/' },
  { name: 'Google AI Studio', primaryCategory: 'Model Tools', secondaryCategory: 'Gemini setup & playground', url: 'https://aistudio.google.com/' },
  { name: 'Google Analytics', primaryCategory: 'Analytics', secondaryCategory: 'Web Analytics', url: 'https://analytics.google.com/' },
  { name: 'Grammarly', primaryCategory: 'Writing', secondaryCategory: 'Grammar Assistant', url: 'https://www.grammarly.com/' },
  { name: 'Gumroad', primaryCategory: 'Marketplace', secondaryCategory: 'Digital Products', url: 'https://gumroad.com/' },
  { name: 'HeyGen', primaryCategory: 'Generative AI', secondaryCategory: 'Video Avatars', url: 'https://www.heygen.com/' },
  { name: 'Hotjar', primaryCategory: 'Analytics', secondaryCategory: 'User Behavior', url: 'https://www.hotjar.com/' },
  { name: 'HubSpot', primaryCategory: 'CRM', secondaryCategory: 'Inbound Marketing', url: 'https://www.hubspot.com/' },
  { name: 'Langflow', primaryCategory: 'AI Framework (No-code)', secondaryCategory: 'Drag-and-drop LLM Flows', url: 'https://www.langflow.org/' },
  { name: 'Linear', primaryCategory: 'Project Management', secondaryCategory: 'Issue Tracking', url: 'https://linear.app/' },
  { name: 'LM Studio', primaryCategory: 'Local Models', secondaryCategory: 'Desktop Runner/UI', url: 'https://lmstudio.ai/' },
  { name: 'LlamaIndex', primaryCategory: 'AI Framework', secondaryCategory: 'RAG/Data Agents', url: 'https://www.llamaindex.ai/' },
  { name: 'Loom', primaryCategory: 'Communications', secondaryCategory: 'Video Messaging/Recording', url: 'https://www.loom.com/' },
  { name: 'Lovable', primaryCategory: 'AI Builders', secondaryCategory: 'App Development', url: 'https://lovable.dev/' },
  { name: 'Make', primaryCategory: 'Automation', secondaryCategory: 'Visual Workflows', url: 'https://www.make.com/' },
  { name: 'Midjourney', primaryCategory: 'AI Models', secondaryCategory: 'Image Generation', url: 'https://www.midjourney.com/' },
  { name: 'Miro', primaryCategory: 'Productivity', secondaryCategory: 'Visual Collaboration', url: 'https://miro.com/' },
  { name: 'Mistral AI', primaryCategory: 'AI Models', secondaryCategory: 'LLM APIs & Models', url: 'https://mistral.ai/' },
  { name: 'Mural', primaryCategory: 'Whiteboard', secondaryCategory: 'Workshops/Facilitation', url: 'https://www.mural.co/' },
  { name: 'Netlify', primaryCategory: 'Hosting/Deploy', secondaryCategory: 'Jamstack Hosting', url: 'https://www.netlify.com/' },
  { name: 'NotebookLM', primaryCategory: 'AI Models', secondaryCategory: 'Document-grounded AI', url: 'https://notebooklm.google/' },
  { name: 'Notion', primaryCategory: 'Productivity', secondaryCategory: 'All-in-one Workspace', url: 'https://www.notion.so/' },
  { name: 'Notion AI', primaryCategory: 'AI Assistant', secondaryCategory: 'Workspace AI', url: 'https://www.notion.com/product/ai' },
  { name: 'n8n', primaryCategory: 'Automation', secondaryCategory: 'Open-source Workflows', url: 'https://n8n.io/' },
  { name: 'Ollama', primaryCategory: 'AI Models', secondaryCategory: 'Local Models', url: 'https://ollama.com/' },
  { name: 'OpenRouter', primaryCategory: 'Model Router', secondaryCategory: 'Multi-provider API', url: 'https://openrouter.ai/' },
  { name: 'Otter.ai', primaryCategory: 'Productivity', secondaryCategory: 'AI Transcription', url: 'https://otter.ai/' },
  { name: 'Pendo', primaryCategory: 'Analytics', secondaryCategory: 'Product Analytics & Guides', url: 'https://www.pendo.io/' },
  { name: 'Perplexity', primaryCategory: 'AI Models', secondaryCategory: 'AI Search/Answer Engine', url: 'https://www.perplexity.ai/' },
  { name: 'Pipedrive', primaryCategory: 'CRM', secondaryCategory: 'Sales Pipeline', url: 'https://www.pipedrive.com/' },
  { name: 'PostHog', primaryCategory: 'Analytics', secondaryCategory: 'Product Analytics/Flags', url: 'https://posthog.com/' },
  { name: 'Productboard', primaryCategory: 'Product Management', secondaryCategory: 'Prioritization & Roadmaps', url: 'https://www.productboard.com/' },
  { name: 'Replit', primaryCategory: 'AI Builders', secondaryCategory: 'Cloud IDE & Hosting', url: 'https://replit.com/' },
  { name: 'Runway', primaryCategory: 'Generative AI', secondaryCategory: 'Video Creation/Editing', url: 'https://runwayml.com/' },
  { name: 'Semrush', primaryCategory: 'SEO', secondaryCategory: 'Digital Marketing Suite', url: 'https://www.semrush.com/' },
  { name: 'Shopify', primaryCategory: 'E-commerce', secondaryCategory: 'Online Store Builder', url: 'https://www.shopify.com/' },
  { name: 'Slack', primaryCategory: 'Communications', secondaryCategory: 'Team Messaging', url: 'https://slack.com/' },
  { name: 'Softr', primaryCategory: 'App Builders', secondaryCategory: 'Web Apps/Portals', url: 'https://www.softr.io/' },
  { name: 'Stack AI', primaryCategory: 'AI App Builder', secondaryCategory: 'Visual Pipelines + Hosting', url: 'https://www.stack-ai.com/' },
  { name: 'Stripe', primaryCategory: 'Payments', secondaryCategory: 'Checkout & Billing', url: 'https://stripe.com/' },
  { name: 'Suno', primaryCategory: 'AI Models', secondaryCategory: 'Music Generation', url: 'https://suno.com/' },
  { name: 'Supabase', primaryCategory: 'Backend', secondaryCategory: 'Postgres DB & Auth', url: 'https://supabase.com/' },
  { name: 'Super', primaryCategory: 'Web Builder', secondaryCategory: 'Notion → Website', url: 'https://super.so/' },
  { name: 'Tally', primaryCategory: 'Forms', secondaryCategory: 'Form Builder', url: 'https://tally.so/' },
  { name: 'Typefully', primaryCategory: 'Social Media', secondaryCategory: 'X/Twitter Management', url: 'https://typefully.com/' },
  { name: 'v0 by Vercel', primaryCategory: 'AI Builders', secondaryCategory: 'UI/Frontend', url: 'https://v0.dev/' },
  { name: 'WeWeb', primaryCategory: 'App Builders', secondaryCategory: 'Frontend Builder', url: 'https://www.weweb.io/' },
  { name: 'Whalesync', primaryCategory: 'Data', secondaryCategory: 'No-code Sync/ETL', url: 'https://www.whalesync.com/' },
  { name: 'xAI', primaryCategory: 'AI Models', secondaryCategory: 'Grok', url: 'https://x.ai/' },
  { name: 'Zapier', primaryCategory: 'Automation', secondaryCategory: 'Workflow Automation', url: 'https://zapier.com/' }
];
