
project_id = "whigwajpngjkxohfhvup"

[functions.improve-prompt]
verify_jwt = false

[functions.test-prompt]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.gemini-api]
verify_jwt = false

[functions.anthropic-chat]
verify_jwt = true

[functions.openrouter-chat]
verify_jwt = true

[functions.provider-status]
verify_jwt = true

[functions.openrouter-sync-models]
verify_jwt = true

