
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whigwajpngjkxohfhvup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaWd3YWpwbmdqa3hvaGZodnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODI5ODAsImV4cCI6MjA1OTQ1ODk4MH0.mNN6PhCbvguQ0evhE42A5WhJ7dSI9o3HH1rQVHnzSYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true // Set to true to detect session in URL for OAuth callbacks
  }
});
